### PR TITLE
Adding note on default image name and tag

### PR DESCRIPTION
**Pull request by dewan-ahmed**

### CODE REVIEW

**Review by mtamboli — COMMENTED** [review]
I see a few comments about this doc:

1. We are assuming that customer is using internal registry. They could use any registry. In that case, customer has to find the pushed images in that registry.

2. We refer to the specific version 0.3.2, We may want to replace with latest kabanero version?
curl -s -L https://github.com/kabanero-io/kabanero-operator/releases/download/0.3.2/install.sh | bash 

3. `appsody-deploy –-generate-only` needs to be updated
remove hyphen.  –-generate-only is deprecated. `appsody deploy` will create this file.

**Comment by dewan-ahmed** [comment]
> I see a few comments about this doc:
> 
> 1. We are assuming that customer is using internal registry. They could use any registry. In that case, customer has to find the pushed images in that registry.
> 2. We refer to the specific version 0.3.2, We may want to replace with latest kabanero version?
>    curl -s -L https://github.com/kabanero-io/kabanero-operator/releases/download/0.3.2/install.sh | bash
> 3. `appsody-deploy –-generate-only` needs to be updated
>    remove hyphen.  –-generate-only is deprecated. `appsody deploy` will create this file.

1. Added comment on external image registry.
2. This guide shows the version on which the guide was last tested (multiple times) and hence a newer version is not stated.
3. Removed deprecated part and hyphen.

**Review by mtamboli — APPROVED** [review]
Looks good. Thank you for all the updates. I think it would be nice to state that we tested with this version look for the latest kabanero version at https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html

**Review by mtamboli — APPROVED** [review]
It looks good. But it is recommended by appsody to use `appsody build` instead of `appsody deploy` to generate app-deploy.yaml as --gernerate-only option is deprectaed.

**Comment by dewan-ahmed** [comment]
@mtamboli I made the change to `appsody build`

**Review by mtamboli — APPROVED** [review]

**Review by mtamboli — APPROVED** [review]

**Review by jantley-ibm — APPROVED** [review]

**Pull request merged**
